# Generated by Django 5.0.3 on 2024-03-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('itemcost', models.CharField(max_length=100)),
                ('tot', models.IntegerField()),
                ('totcost', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('orderdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=1000)),
                ('ratingval', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('itemtype', models.CharField(max_length=100)),
                ('itemcost', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('ratingval', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
                ('dat_e', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('yearmonth', models.CharField(max_length=100)),
                ('tamt', models.CharField(max_length=100)),
                ('prod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('yearmonth', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tamt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
    ]
